# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

sudo: false
install:
  - gem install xcop
  - pip install codecov
script:
  - make
after_success:
  - codecov


